### ISSUE TITLE
Issues with previewing KML

### ISSUE THREAD

**Issue by d41k4n** [bm98/XPVTraffic#1] opened 2021-04-01 21:08 UTC
I'm unable to import the written KML file into Google Earth or Google Maps (GE freezes and GM ends up with bogus lat/lon coordinates that are way out of bounds).

It seems the LineString coordinates don't make much sense and the decimal notation uses commas instead of dots as per the [KML 2.2 reference example](https://developers.google.com/kml/documentation/kmlreference#example_11).

Find attached the resulting KML file for the bundled `AcroRound-LSZH_RW14.vsc` script:

[AcroRound-LSZH_RW14.vsc.kml.zip](https://github.com/bm98/XPVTraffic/files/6246442/AcroRound-LSZH_RW14.vsc.kml.zip)

**Comment by bm98** [comment] 2021-04-02 12:00
If commas instead of decimal points are inserted it points to a locale issue.
Seems your locale would use decimal commas and the program does not force the locale to be 'neutral' in order to format numbers with decimal points.
Have to look into it and fix it..
Would you be able to let me know which locale (country setting) your computer is set to - just to confirm the root cause

**Comment by bm98** [comment] 2021-04-02 12:16
I've added the locale fix - could you confirm? Then I will upload the update
Just drop the zipped exe and dll into the current app folder
Thanks

[XPTsim-0.9.0.10.zip](https://github.com/bm98/XPVTraffic/files/6249451/XPTsim-0.9.0.10.zip)

**Comment by d41k4n** [comment] 2021-04-02 17:57
Thanks a lot - that fixes the KML so it can be imported and visualized in other tools.

FYI: I also had to re-create the airway/runway database as it suffered from the same issue (without re-creating it the KML's geolocation was completely wrong).

**Comment by bm98** [comment] 2021-04-02 22:06
Fix released as Version 0.10 Build 10

**Closed as completed by bm98** 2021-04-02 22:06 UTC
